my.greeting =Hello Bikash!!
app.name = Spring Boot
#app.description =${app.name} application
my.list.values=one,two,three
dbvalues = {connectionString:'http:________',userName:'foo',password:'foo'}
db.connection = {connectionString:'http:________',userName:'foo',password:'foo'}
db.host = 127.0.0.1
db.port = 1500
management.endpoints.web.exposure.include=*